//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokMVC.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSTOKEntities : DbContext
    {
        public dbSTOKEntities()
            : base("name=dbSTOKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblKATEGORI> tblKATEGORI { get; set; }
        public virtual DbSet<tblMUSTERI> tblMUSTERI { get; set; }
        public virtual DbSet<tblPERSONEL> tblPERSONEL { get; set; }
        public virtual DbSet<tblSATISLAR> tblSATISLAR { get; set; }
        public virtual DbSet<tblURUNLER> tblURUNLER { get; set; }
        public virtual DbSet<tblADMIN> tblADMIN { get; set; }
    }
}
